# Generated by Django 2.1.3 on 2018-12-21 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default=1, on_delete=0, to=settings.AUTH_USER_MODEL),
        ),
    ]
